<?php
/**
 * Migration: Seed Countries Data
 * Created: 2025-10-11
 * Description: Populate countries table with all 192+ countries with ISO codes, dialing codes, currencies
 * Data includes: Rwanda (+250, RWF), all EU member states, and rest of world
 */

return [
    'up' => "
        INSERT INTO `countries` (`name`, `iso2`, `iso3`, `dial_code`, `is_eu`, `currency_code`, `currency_symbol`, `flag_emoji`) VALUES
        ('Afghanistan', 'AF', 'AFG', '+93', 0, 'USD', '\$', '🇦🇫'),
        ('Albania', 'AL', 'ALB', '+355', 0, 'USD', '\$', '🇦🇱'),
        ('Algeria', 'DZ', 'DZA', '+213', 0, 'USD', '\$', '🇩🇿'),
        ('Andorra', 'AD', 'AND', '+376', 0, 'EUR', '€', '🇦🇩'),
        ('Angola', 'AO', 'AGO', '+244', 0, 'USD', '\$', '🇦🇴'),
        ('Antigua and Barbuda', 'AG', 'ATG', '+1268', 0, 'USD', '\$', '🇦🇬'),
        ('Argentina', 'AR', 'ARG', '+54', 0, 'USD', '\$', '🇦🇷'),
        ('Armenia', 'AM', 'ARM', '+374', 0, 'USD', '\$', '🇦🇲'),
        ('Australia', 'AU', 'AUS', '+61', 0, 'USD', '\$', '🇦🇺'),
        ('Austria', 'AT', 'AUT', '+43', 1, 'EUR', '€', '🇦🇹'),
        ('Azerbaijan', 'AZ', 'AZE', '+994', 0, 'USD', '\$', '🇦🇿'),
        ('Bahamas', 'BS', 'BHS', '+1242', 0, 'USD', '\$', '🇧🇸'),
        ('Bahrain', 'BH', 'BHR', '+973', 0, 'USD', '\$', '🇧🇭'),
        ('Bangladesh', 'BD', 'BGD', '+880', 0, 'USD', '\$', '🇧🇩'),
        ('Barbados', 'BB', 'BRB', '+1246', 0, 'USD', '\$', '🇧🇧'),
        ('Belarus', 'BY', 'BLR', '+375', 0, 'USD', '\$', '🇧🇾'),
        ('Belgium', 'BE', 'BEL', '+32', 1, 'EUR', '€', '🇧🇪'),
        ('Belize', 'BZ', 'BLZ', '+501', 0, 'USD', '\$', '🇧🇿'),
        ('Benin', 'BJ', 'BEN', '+229', 0, 'USD', '\$', '🇧🇯'),
        ('Bhutan', 'BT', 'BTN', '+975', 0, 'USD', '\$', '🇧🇹'),
        ('Bolivia', 'BO', 'BOL', '+591', 0, 'USD', '\$', '🇧🇴'),
        ('Bosnia and Herzegovina', 'BA', 'BIH', '+387', 0, 'USD', '\$', '🇧🇦'),
        ('Botswana', 'BW', 'BWA', '+267', 0, 'USD', '\$', '🇧🇼'),
        ('Brazil', 'BR', 'BRA', '+55', 0, 'USD', '\$', '🇧🇷'),
        ('Brunei', 'BN', 'BRN', '+673', 0, 'USD', '\$', '🇧🇳'),
        ('Bulgaria', 'BG', 'BGR', '+359', 1, 'EUR', '€', '🇧🇬'),
        ('Burkina Faso', 'BF', 'BFA', '+226', 0, 'USD', '\$', '🇧🇫'),
        ('Burundi', 'BI', 'BDI', '+257', 0, 'USD', '\$', '🇧🇮'),
        ('Cambodia', 'KH', 'KHM', '+855', 0, 'USD', '\$', '🇰🇭'),
        ('Cameroon', 'CM', 'CMR', '+237', 0, 'USD', '\$', '🇨🇲'),
        ('Canada', 'CA', 'CAN', '+1', 0, 'USD', '\$', '🇨🇦'),
        ('Cape Verde', 'CV', 'CPV', '+238', 0, 'USD', '\$', '🇨🇻'),
        ('Central African Republic', 'CF', 'CAF', '+236', 0, 'USD', '\$', '🇨🇫'),
        ('Chad', 'TD', 'TCD', '+235', 0, 'USD', '\$', '🇹🇩'),
        ('Chile', 'CL', 'CHL', '+56', 0, 'USD', '\$', '🇨🇱'),
        ('China', 'CN', 'CHN', '+86', 0, 'USD', '\$', '🇨🇳'),
        ('Colombia', 'CO', 'COL', '+57', 0, 'USD', '\$', '🇨🇴'),
        ('Comoros', 'KM', 'COM', '+269', 0, 'USD', '\$', '🇰🇲'),
        ('Congo', 'CG', 'COG', '+242', 0, 'USD', '\$', '🇨🇬'),
        ('Costa Rica', 'CR', 'CRI', '+506', 0, 'USD', '\$', '🇨🇷'),
        ('Croatia', 'HR', 'HRV', '+385', 1, 'EUR', '€', '🇭🇷'),
        ('Cuba', 'CU', 'CUB', '+53', 0, 'USD', '\$', '🇨🇺'),
        ('Cyprus', 'CY', 'CYP', '+357', 1, 'EUR', '€', '🇨🇾'),
        ('Czech Republic', 'CZ', 'CZE', '+420', 1, 'EUR', '€', '🇨🇿'),
        ('Denmark', 'DK', 'DNK', '+45', 1, 'EUR', '€', '🇩🇰'),
        ('Djibouti', 'DJ', 'DJI', '+253', 0, 'USD', '\$', '🇩🇯'),
        ('Dominica', 'DM', 'DMA', '+1767', 0, 'USD', '\$', '🇩🇲'),
        ('Dominican Republic', 'DO', 'DOM', '+1', 0, 'USD', '\$', '🇩🇴'),
        ('Ecuador', 'EC', 'ECU', '+593', 0, 'USD', '\$', '🇪🇨'),
        ('Egypt', 'EG', 'EGY', '+20', 0, 'USD', '\$', '🇪🇬'),
        ('El Salvador', 'SV', 'SLV', '+503', 0, 'USD', '\$', '🇸🇻'),
        ('Equatorial Guinea', 'GQ', 'GNQ', '+240', 0, 'USD', '\$', '🇬🇶'),
        ('Eritrea', 'ER', 'ERI', '+291', 0, 'USD', '\$', '🇪🇷'),
        ('Estonia', 'EE', 'EST', '+372', 1, 'EUR', '€', '🇪🇪'),
        ('Ethiopia', 'ET', 'ETH', '+251', 0, 'USD', '\$', '🇪🇹'),
        ('Fiji', 'FJ', 'FJI', '+679', 0, 'USD', '\$', '🇫🇯'),
        ('Finland', 'FI', 'FIN', '+358', 1, 'EUR', '€', '🇫🇮'),
        ('France', 'FR', 'FRA', '+33', 1, 'EUR', '€', '🇫🇷'),
        ('Gabon', 'GA', 'GAB', '+241', 0, 'USD', '\$', '🇬🇦'),
        ('Gambia', 'GM', 'GMB', '+220', 0, 'USD', '\$', '🇬🇲'),
        ('Georgia', 'GE', 'GEO', '+995', 0, 'USD', '\$', '🇬🇪'),
        ('Germany', 'DE', 'DEU', '+49', 1, 'EUR', '€', '🇩🇪'),
        ('Ghana', 'GH', 'GHA', '+233', 0, 'USD', '\$', '🇬🇭'),
        ('Greece', 'GR', 'GRC', '+30', 1, 'EUR', '€', '🇬🇷'),
        ('Grenada', 'GD', 'GRD', '+1473', 0, 'USD', '\$', '🇬🇩'),
        ('Guatemala', 'GT', 'GTM', '+502', 0, 'USD', '\$', '🇬🇹'),
        ('Guinea', 'GN', 'GIN', '+224', 0, 'USD', '\$', '🇬🇳'),
        ('Guinea-Bissau', 'GW', 'GNB', '+245', 0, 'USD', '\$', '🇬🇼'),
        ('Guyana', 'GY', 'GUY', '+592', 0, 'USD', '\$', '🇬🇾'),
        ('Haiti', 'HT', 'HTI', '+509', 0, 'USD', '\$', '🇭🇹'),
        ('Honduras', 'HN', 'HND', '+504', 0, 'USD', '\$', '🇭🇳'),
        ('Hungary', 'HU', 'HUN', '+36', 1, 'EUR', '€', '🇭🇺'),
        ('Iceland', 'IS', 'ISL', '+354', 0, 'USD', '\$', '🇮🇸'),
        ('India', 'IN', 'IND', '+91', 0, 'USD', '\$', '🇮🇳'),
        ('Indonesia', 'ID', 'IDN', '+62', 0, 'USD', '\$', '🇮🇩'),
        ('Iran', 'IR', 'IRN', '+98', 0, 'USD', '\$', '🇮🇷'),
        ('Iraq', 'IQ', 'IRQ', '+964', 0, 'USD', '\$', '🇮🇶'),
        ('Ireland', 'IE', 'IRL', '+353', 1, 'EUR', '€', '🇮🇪'),
        ('Israel', 'IL', 'ISR', '+972', 0, 'USD', '\$', '🇮🇱'),
        ('Italy', 'IT', 'ITA', '+39', 1, 'EUR', '€', '🇮🇹'),
        ('Jamaica', 'JM', 'JAM', '+1876', 0, 'USD', '\$', '🇯🇲'),
        ('Japan', 'JP', 'JPN', '+81', 0, 'USD', '\$', '🇯🇵'),
        ('Jordan', 'JO', 'JOR', '+962', 0, 'USD', '\$', '🇯🇴'),
        ('Kazakhstan', 'KZ', 'KAZ', '+7', 0, 'USD', '\$', '🇰🇿'),
        ('Kenya', 'KE', 'KEN', '+254', 0, 'USD', '\$', '🇰🇪'),
        ('Kiribati', 'KI', 'KIR', '+686', 0, 'USD', '\$', '🇰🇮'),
        ('Kuwait', 'KW', 'KWT', '+965', 0, 'USD', '\$', '🇰🇼'),
        ('Kyrgyzstan', 'KG', 'KGZ', '+996', 0, 'USD', '\$', '🇰🇬'),
        ('Laos', 'LA', 'LAO', '+856', 0, 'USD', '\$', '🇱🇦'),
        ('Latvia', 'LV', 'LVA', '+371', 1, 'EUR', '€', '🇱🇻'),
        ('Lebanon', 'LB', 'LBN', '+961', 0, 'USD', '\$', '🇱🇧'),
        ('Lesotho', 'LS', 'LSO', '+266', 0, 'USD', '\$', '🇱🇸'),
        ('Liberia', 'LR', 'LBR', '+231', 0, 'USD', '\$', '🇱🇷'),
        ('Libya', 'LY', 'LBY', '+218', 0, 'USD', '\$', '🇱🇾'),
        ('Liechtenstein', 'LI', 'LIE', '+423', 0, 'USD', '\$', '🇱🇮'),
        ('Lithuania', 'LT', 'LTU', '+370', 1, 'EUR', '€', '🇱🇹'),
        ('Luxembourg', 'LU', 'LUX', '+352', 1, 'EUR', '€', '🇱🇺'),
        ('Macedonia', 'MK', 'MKD', '+389', 0, 'USD', '\$', '🇲🇰'),
        ('Madagascar', 'MG', 'MDG', '+261', 0, 'USD', '\$', '🇲🇬'),
        ('Malawi', 'MW', 'MWI', '+265', 0, 'USD', '\$', '🇲🇼'),
        ('Malaysia', 'MY', 'MYS', '+60', 0, 'USD', '\$', '🇲🇾'),
        ('Maldives', 'MV', 'MDV', '+960', 0, 'USD', '\$', '🇲🇻'),
        ('Mali', 'ML', 'MLI', '+223', 0, 'USD', '\$', '🇲🇱'),
        ('Malta', 'MT', 'MLT', '+356', 1, 'EUR', '€', '🇲🇹'),
        ('Marshall Islands', 'MH', 'MHL', '+692', 0, 'USD', '\$', '🇲🇭'),
        ('Mauritania', 'MR', 'MRT', '+222', 0, 'USD', '\$', '🇲🇷'),
        ('Mauritius', 'MU', 'MUS', '+230', 0, 'USD', '\$', '🇲🇺'),
        ('Mexico', 'MX', 'MEX', '+52', 0, 'USD', '\$', '🇲🇽'),
        ('Micronesia', 'FM', 'FSM', '+691', 0, 'USD', '\$', '🇫🇲'),
        ('Moldova', 'MD', 'MDA', '+373', 0, 'USD', '\$', '🇲🇩'),
        ('Monaco', 'MC', 'MCO', '+377', 0, 'EUR', '€', '🇲🇨'),
        ('Mongolia', 'MN', 'MNG', '+976', 0, 'USD', '\$', '🇲🇳'),
        ('Montenegro', 'ME', 'MNE', '+382', 0, 'EUR', '€', '🇲🇪'),
        ('Morocco', 'MA', 'MAR', '+212', 0, 'USD', '\$', '🇲🇦'),
        ('Mozambique', 'MZ', 'MOZ', '+258', 0, 'USD', '\$', '🇲🇿'),
        ('Myanmar', 'MM', 'MMR', '+95', 0, 'USD', '\$', '🇲🇲'),
        ('Namibia', 'NA', 'NAM', '+264', 0, 'USD', '\$', '🇳🇦'),
        ('Nauru', 'NR', 'NRU', '+674', 0, 'USD', '\$', '🇳🇷'),
        ('Nepal', 'NP', 'NPL', '+977', 0, 'USD', '\$', '🇳🇵'),
        ('Netherlands', 'NL', 'NLD', '+31', 1, 'EUR', '€', '🇳🇱'),
        ('New Zealand', 'NZ', 'NZL', '+64', 0, 'USD', '\$', '🇳🇿'),
        ('Nicaragua', 'NI', 'NIC', '+505', 0, 'USD', '\$', '🇳🇮'),
        ('Niger', 'NE', 'NER', '+227', 0, 'USD', '\$', '🇳🇪'),
        ('Nigeria', 'NG', 'NGA', '+234', 0, 'USD', '\$', '🇳🇬'),
        ('Norway', 'NO', 'NOR', '+47', 0, 'USD', '\$', '🇳🇴'),
        ('Oman', 'OM', 'OMN', '+968', 0, 'USD', '\$', '🇴🇲'),
        ('Pakistan', 'PK', 'PAK', '+92', 0, 'USD', '\$', '🇵🇰'),
        ('Palau', 'PW', 'PLW', '+680', 0, 'USD', '\$', '🇵🇼'),
        ('Panama', 'PA', 'PAN', '+507', 0, 'USD', '\$', '🇵🇦'),
        ('Papua New Guinea', 'PG', 'PNG', '+675', 0, 'USD', '\$', '🇵🇬'),
        ('Paraguay', 'PY', 'PRY', '+595', 0, 'USD', '\$', '🇵🇾'),
        ('Peru', 'PE', 'PER', '+51', 0, 'USD', '\$', '🇵🇪'),
        ('Philippines', 'PH', 'PHL', '+63', 0, 'USD', '\$', '🇵🇭'),
        ('Poland', 'PL', 'POL', '+48', 1, 'EUR', '€', '🇵🇱'),
        ('Portugal', 'PT', 'PRT', '+351', 1, 'EUR', '€', '🇵🇹'),
        ('Qatar', 'QA', 'QAT', '+974', 0, 'USD', '\$', '🇶🇦'),
        ('Romania', 'RO', 'ROU', '+40', 1, 'EUR', '€', '🇷🇴'),
        ('Russia', 'RU', 'RUS', '+7', 0, 'USD', '\$', '🇷🇺'),
        ('Rwanda', 'RW', 'RWA', '+250', 0, 'RWF', 'FRw', '🇷🇼'),
        ('Saint Kitts and Nevis', 'KN', 'KNA', '+1869', 0, 'USD', '\$', '🇰🇳'),
        ('Saint Lucia', 'LC', 'LCA', '+1758', 0, 'USD', '\$', '🇱🇨'),
        ('Saint Vincent and the Grenadines', 'VC', 'VCT', '+1784', 0, 'USD', '\$', '🇻🇨'),
        ('Samoa', 'WS', 'WSM', '+685', 0, 'USD', '\$', '🇼🇸'),
        ('San Marino', 'SM', 'SMR', '+378', 0, 'EUR', '€', '🇸🇲'),
        ('Sao Tome and Principe', 'ST', 'STP', '+239', 0, 'USD', '\$', '🇸🇹'),
        ('Saudi Arabia', 'SA', 'SAU', '+966', 0, 'USD', '\$', '🇸🇦'),
        ('Senegal', 'SN', 'SEN', '+221', 0, 'USD', '\$', '🇸🇳'),
        ('Serbia', 'RS', 'SRB', '+381', 0, 'USD', '\$', '🇷🇸'),
        ('Seychelles', 'SC', 'SYC', '+248', 0, 'USD', '\$', '🇸🇨'),
        ('Sierra Leone', 'SL', 'SLE', '+232', 0, 'USD', '\$', '🇸🇱'),
        ('Singapore', 'SG', 'SGP', '+65', 0, 'USD', '\$', '🇸🇬'),
        ('Slovakia', 'SK', 'SVK', '+421', 1, 'EUR', '€', '🇸🇰'),
        ('Slovenia', 'SI', 'SVN', '+386', 1, 'EUR', '€', '🇸🇮'),
        ('Solomon Islands', 'SB', 'SLB', '+677', 0, 'USD', '\$', '🇸🇧'),
        ('Somalia', 'SO', 'SOM', '+252', 0, 'USD', '\$', '🇸🇴'),
        ('South Africa', 'ZA', 'ZAF', '+27', 0, 'USD', '\$', '🇿🇦'),
        ('South Korea', 'KR', 'KOR', '+82', 0, 'USD', '\$', '🇰🇷'),
        ('South Sudan', 'SS', 'SSD', '+211', 0, 'USD', '\$', '🇸🇸'),
        ('Spain', 'ES', 'ESP', '+34', 1, 'EUR', '€', '🇪🇸'),
        ('Sri Lanka', 'LK', 'LKA', '+94', 0, 'USD', '\$', '🇱🇰'),
        ('Sudan', 'SD', 'SDN', '+249', 0, 'USD', '\$', '🇸🇩'),
        ('Suriname', 'SR', 'SUR', '+597', 0, 'USD', '\$', '🇸🇷'),
        ('Swaziland', 'SZ', 'SWZ', '+268', 0, 'USD', '\$', '🇸🇿'),
        ('Sweden', 'SE', 'SWE', '+46', 1, 'EUR', '€', '🇸🇪'),
        ('Switzerland', 'CH', 'CHE', '+41', 0, 'USD', '\$', '🇨🇭'),
        ('Syria', 'SY', 'SYR', '+963', 0, 'USD', '\$', '🇸🇾'),
        ('Taiwan', 'TW', 'TWN', '+886', 0, 'USD', '\$', '🇹🇼'),
        ('Tajikistan', 'TJ', 'TJK', '+992', 0, 'USD', '\$', '🇹🇯'),
        ('Tanzania', 'TZ', 'TZA', '+255', 0, 'USD', '\$', '🇹🇿'),
        ('Thailand', 'TH', 'THA', '+66', 0, 'USD', '\$', '🇹🇭'),
        ('Timor-Leste', 'TL', 'TLS', '+670', 0, 'USD', '\$', '🇹🇱'),
        ('Togo', 'TG', 'TGO', '+228', 0, 'USD', '\$', '🇹🇬'),
        ('Tonga', 'TO', 'TON', '+676', 0, 'USD', '\$', '🇹🇴'),
        ('Trinidad and Tobago', 'TT', 'TTO', '+1868', 0, 'USD', '\$', '🇹🇹'),
        ('Tunisia', 'TN', 'TUN', '+216', 0, 'USD', '\$', '🇹🇳'),
        ('Turkey', 'TR', 'TUR', '+90', 0, 'USD', '\$', '🇹🇷'),
        ('Turkmenistan', 'TM', 'TKM', '+993', 0, 'USD', '\$', '🇹🇲'),
        ('Tuvalu', 'TV', 'TUV', '+688', 0, 'USD', '\$', '🇹🇻'),
        ('Uganda', 'UG', 'UGA', '+256', 0, 'USD', '\$', '🇺🇬'),
        ('Ukraine', 'UA', 'UKR', '+380', 0, 'USD', '\$', '🇺🇦'),
        ('United Arab Emirates', 'AE', 'ARE', '+971', 0, 'USD', '\$', '🇦🇪'),
        ('United Kingdom', 'GB', 'GBR', '+44', 0, 'GBP', '£', '🇬🇧'),
        ('United States', 'US', 'USA', '+1', 0, 'USD', '\$', '🇺🇸'),
        ('Uruguay', 'UY', 'URY', '+598', 0, 'USD', '\$', '🇺🇾'),
        ('Uzbekistan', 'UZ', 'UZB', '+998', 0, 'USD', '\$', '🇺🇿'),
        ('Vanuatu', 'VU', 'VUT', '+678', 0, 'USD', '\$', '🇻🇺'),
        ('Vatican City', 'VA', 'VAT', '+39', 0, 'EUR', '€', '🇻🇦'),
        ('Venezuela', 'VE', 'VEN', '+58', 0, 'USD', '\$', '🇻🇪'),
        ('Vietnam', 'VN', 'VNM', '+84', 0, 'USD', '\$', '🇻🇳'),
        ('Yemen', 'YE', 'YEM', '+967', 0, 'USD', '\$', '🇾🇪'),
        ('Zambia', 'ZM', 'ZMB', '+260', 0, 'USD', '\$', '🇿🇲'),
        ('Zimbabwe', 'ZW', 'ZWE', '+263', 0, 'USD', '\$', '🇿🇼')
        ON DUPLICATE KEY UPDATE
            `name` = VALUES(`name`),
            `dial_code` = VALUES(`dial_code`),
            `is_eu` = VALUES(`is_eu`),
            `currency_code` = VALUES(`currency_code`),
            `currency_symbol` = VALUES(`currency_symbol`),
            `flag_emoji` = VALUES(`flag_emoji`),
            `updated_at` = CURRENT_TIMESTAMP;
    ",
    
    'down' => "
        DELETE FROM `countries` WHERE `iso2` IN (
            'AF','AL','DZ','AD','AO','AG','AR','AM','AU','AT','AZ','BS','BH','BD','BB','BY','BE','BZ','BJ','BT',
            'BO','BA','BW','BR','BN','BG','BF','BI','KH','CM','CA','CV','CF','TD','CL','CN','CO','KM','CG','CR',
            'HR','CU','CY','CZ','DK','DJ','DM','DO','EC','EG','SV','GQ','ER','EE','ET','FJ','FI','FR','GA','GM',
            'GE','DE','GH','GR','GD','GT','GN','GW','GY','HT','HN','HU','IS','IN','ID','IR','IQ','IE','IL','IT',
            'JM','JP','JO','KZ','KE','KI','KW','KG','LA','LV','LB','LS','LR','LY','LI','LT','LU','MK','MG','MW',
            'MY','MV','ML','MT','MH','MR','MU','MX','FM','MD','MC','MN','ME','MA','MZ','MM','NA','NR','NP','NL',
            'NZ','NI','NE','NG','NO','OM','PK','PW','PA','PG','PY','PE','PH','PL','PT','QA','RO','RU','RW','KN',
            'LC','VC','WS','SM','ST','SA','SN','RS','SC','SL','SG','SK','SI','SB','SO','ZA','KR','SS','ES','LK',
            'SD','SR','SZ','SE','CH','SY','TW','TJ','TZ','TH','TL','TG','TO','TT','TN','TR','TM','TV','UG','UA',
            'AE','GB','US','UY','UZ','VU','VA','VE','VN','YE','ZM','ZW'
        );
    "
];
